### PR TITLE
Temperature Converter

### PR DESCRIPTION
**Pull request by Srishti-j18**
Task 24

### CODE REVIEW

**Comment by Srishti-j18** [comment]
Hello Bhaiya, 
  I updated the code, please review and merge my PR.

**Comment by Srishti-j18** [comment]
Bhaiya ,Task 26 done ,please review.

**Comment by james3gh** [comment]
@Srishti-j18 nice work...you can try to make code less redundant in task 24 using function for C/F. Also you can use ES6 now

**Comment by Srishti-j18** [comment]
> @Srishti-j18 nice work...you can try to make code less redundant in task 24 using function for C/F. Also you can use ES6 now

Ok bhaiya, I will do.

**Pull request merged**
