### PR TITLE
17 pe khatra

### PR DESCRIPTION
**Pull request by Srishti-j18**
Issue: 17 pe khatra_42

### CODE REVIEW

**Comment by james3gh** [comment]
@Srishti-j18 would you like to try this issue now ? or should I close this PR

**Comment by Srishti-j18** [comment]
> @Srishti-j18 would you like to try this issue now ? or should I close this PR

Sorry Bhaiya, Actually I was tired yesterday and I am traveling rn, So can you give me some more time ? Pls don't close the PR , I will try.

**Comment by Srishti-j18** [comment]
> > @Srishti-j18 would you like to try this issue now ? or should I close this PR
> 
> Sorry Bhaiya, Actually I was tired yesterday and I am traveling rn, So can you give me some more time ? Pls don't close the PR , I will try.

Bhaiya Pls review my task

**Comment by james3gh** [comment]
@Srishti-j18 please solve the merge conflicts

**Comment by james3gh** [comment]
@Srishti-j18 grt work 🙌

**Pull request merged**
